# use version 2 of the docker compose syntax
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: .docker/app.dockerfile

    image: test_stickers.local
    
    ports:
        - 8280:80
    
    volumes:
      - /home/ibm/Stickers/app:/var/www/html
    
    depends_on:
      - db
    
    links:
      - db
  
  db:
    # use a default image
    image: mariadb

    ports:
      - 13309:3306

    environment:
      MYSQL_USERNAME: examplepass
      MYSQL_ROOT_PASSWORD: examplepass

  phpmyadmin: #por un puto espacio no anda el archivo del re culo :c
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 8281:80
    volumes:
      - /sessions
    links:
      - db